# -*- coding: utf-8 -*-
"""cuda vector.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM-EK_yVLlLt_3nPnciOqhBRQicsQpFE
"""

# Commented out IPython magic to ensure Python compatibility.
!nvcc --version
!pip install git+https://github.com/afnan47/cuda.git
# %load_ext nvcc_plugin

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# using namespace std;
# 
# __global__ void add(int* A, int* B, int* C, int size) {
#     int tid = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     if (tid < size) {
#         C[tid] = A[tid] + B[tid];
#     }
# }
# 
# 
# /* -------- INITIALIZE VECTOR -------- */
# void initialize(int* vector, int size) {
#     for (int i = 0; i < size; i++) {
#         vector[i] = rand() % 10;
#     }
# }
# 
# /* -------- PRINT VECTOR -------- */
# void print(int* vector, int size) {
#     for (int i = 0; i < size; i++) {
#         cout << vector[i] << " ";
#     }
#     cout << endl;
# }
# 
# /* -------- MAIN FUNCTION -------- */
# int main() {
#     int N = 4;
#     int vectorSize = N;
#     size_t vectorBytes = vectorSize * sizeof(int);
# 
#     int *A, *B, *C;
# 
#     // Allocate host memory
#     A = new int[vectorSize];
#     B = new int[vectorSize];
#     C = new int[vectorSize];
# 
#     // Initialize vectors
#     initialize(A, vectorSize);
#     initialize(B, vectorSize);
# 
#     cout << "Vector A: ";
#     print(A, N);
# 
#     cout << "Vector B: ";
#     print(B, N);
# 
#     // Device pointers
#     int *X, *Y, *Z;
# 
#     // Allocate GPU memory
#     cudaMalloc(&X, vectorBytes);
#     cudaMalloc(&Y, vectorBytes);
#     cudaMalloc(&Z, vectorBytes);
# 
#     // Copy data from CPU to GPU
#     cudaMemcpy(X, A, vectorBytes, cudaMemcpyHostToDevice);
#     cudaMemcpy(Y, B, vectorBytes, cudaMemcpyHostToDevice);
# 
#     // Define threads and blocks
#     int threadsPerBlock = 256;
#     int blocksPerGrid = (N + threadsPerBlock - 1) / threadsPerBlock;
# 
#     // Launch kernel
#     add<<<blocksPerGrid, threadsPerBlock>>>(X, Y, Z, N);
# 
#     // Copy result back to CPU
#     cudaMemcpy(C, Z, vectorBytes, cudaMemcpyDeviceToHost);
# 
#     cout << "Addition: ";
#     print(C, N);
# 
#     // Free memory
#     delete[] A;
#     delete[] B;
#     delete[] C;
# 
#     cudaFree(X);
#     cudaFree(Y);
#     cudaFree(Z);
# 
#     return 0;
# }

