# -*- coding: utf-8 -*-
"""cuda matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cM-EK_yVLlLt_3nPnciOqhBRQicsQpFE
"""

# Commented out IPython magic to ensure Python compatibility.
!nvcc --version
!pip install git+https://github.com/afnan47/cuda.git
# %load_ext nvcc_plugin

# Commented out IPython magic to ensure Python compatibility.
# %%cu
# #include <iostream>
# #include <cuda.h>
# 
# using namespace std;
# 
# #define BLOCK_SIZE 2
# 
# /* -------- CUDA KERNEL -------- */
# __global__ void gpuMM(float *A, float *B, float *C, int N) {
# 
#     int row = blockIdx.y * blockDim.y + threadIdx.y;
#     int col = blockIdx.x * blockDim.x + threadIdx.x;
# 
#     float sum = 0.0f;
# 
#     for (int n = 0; n < N; ++n) {
#         sum += A[row * N + n] * B[n * N + col];
#     }
# 
#     C[row * N + col] = sum;
# }
# 
# /* -------- MAIN FUNCTION -------- */
# int main() {
# 
#     int N;
#     float K;
# 
#     cout << "Enter a value for Size/2 of matrix: ";
#     cin >> K;
# 
#     K = 1;   // fixed for demo
#     N = K * BLOCK_SIZE;
# 
#     cout << "\nExecuting Matrix Multiplication\n";
#     cout << "Matrix size: " << N << " x " << N << endl;
# 
#     /* -------- HOST MEMORY -------- */
#     float *hA, *hB, *hC;
# 
#     hA = new float[N * N];
#     hB = new float[N * N];
#     hC = new float[N * N];
# 
#     /* -------- INITIALIZE MATRICES -------- */
#     for (int i = 0; i < N * N; i++) {
#         hA[i] = 2;
#         hB[i] = 4;
#     }
# 
#     /* -------- DEVICE MEMORY -------- */
#     float *dA, *dB, *dC;
#     int size = N * N * sizeof(float);
# 
#     cudaMalloc(&dA, size);
#     cudaMalloc(&dB, size);
#     cudaMalloc(&dC, size);
# 
#     /* -------- COPY DATA TO GPU -------- */
#     cudaMemcpy(dA, hA, size, cudaMemcpyHostToDevice);
#     cudaMemcpy(dB, hB, size, cudaMemcpyHostToDevice);
# 
#     /* -------- THREADS & BLOCKS -------- */
#     dim3 threadBlock(BLOCK_SIZE, BLOCK_SIZE);
#     dim3 grid(K, K);
# 
#     /* -------- PRINT INPUT MATRICES -------- */
#     cout << "\nMatrix A:\n";
#     for (int row = 0; row < N; row++) {
#         for (int col = 0; col < N; col++) {
#             cout << hA[row * N + col] << " ";
#         }
#         cout << endl;
#     }
# 
#     cout << "\nMatrix B:\n";
#     for (int row = 0; row < N; row++) {
#         for (int col = 0; col < N; col++) {
#             cout << hB[row * N + col] << " ";
#         }
#         cout << endl;
#     }
# 
#     /* -------- KERNEL CALL -------- */
#     gpuMM<<<grid, threadBlock>>>(dA, dB, dC, N);
# 
#     /* -------- COPY RESULT BACK -------- */
#     float *C = new float[N * N];
#     cudaMemcpy(C, dC, size, cudaMemcpyDeviceToHost);
# 
#     /* -------- PRINT RESULT -------- */
#     cout << "\nResultant Matrix:\n";
#     for (int row = 0; row < N; row++) {
#         for (int col = 0; col < N; col++) {
#             cout << C[row * N + col] << " ";
#         }
#         cout << endl;
#     }
# 
#     cout << "\nFinished.\n";
# 
#     /* -------- FREE MEMORY -------- */
#     delete[] hA;
#     delete[] hB;
#     delete[] hC;
#     delete[] C;
# 
#     cudaFree(dA);
#     cudaFree(dB);
#     cudaFree(dC);
# 
#     return 0;
# }

